import assert from "node:assert/strict";
import test from "node:test";
import { isAwardedBidder, normalizeBidderName, parseBidassistAmount, parseBidderRank } from "../bidassistResultParser.js";
import { mergeBidassistResultMetadata, parseBidassistResultMetadata, preserveBidassistResultMetadata } from "../bidassistResultMetadata.js";
test("parses BidAssist Indian amounts without losing raw display", () => { const p = parseBidassistAmount("₹ 4.2 Lac"); assert.equal(p.display, "₹ 4.2 Lac"); assert.equal(p.normalized, 420000); assert.equal(p.currency, "INR"); assert.equal(parseBidassistAmount("Rs. 1.25 Crore").normalized, 12500000); assert.equal(parseBidassistAmount("INR 20 Thousand").normalized, 20000); });
test("parses ranks and awarded signal defensively", () => { assert.equal(parseBidderRank("₹4.2 Lac (L1)"), "L1"); assert.equal(parseBidderRank("no rank"), null); assert.equal(isAwardedBidder("Accepted-Aoc Awarded"), true); assert.equal(isAwardedBidder("Rejected-Financial"), false); });
test("normalizes bidder identity for repeat-run upserts", () => { assert.equal(normalizeBidderName(" Siyana Info Solutions Private Limited "), "siyana info solutions private limited"); assert.equal(normalizeBidderName("Siyana-Info Solutions, Pvt. Ltd."), "siyana info solutions pvt ltd"); });
test("parses and preserves search-card result metadata when detail omits it", () => { const card = parseBidassistResultMetadata("Award ID: GEM/2026/B/7885291\nResult Stage:  Under Evaluation \nContract Date: 8 Sep 2026"); assert.deepEqual(card, { stage: "Under Evaluation", contractDate: "8 Sep 2026" }); const merged = mergeBidassistResultMetadata(card, { stage: null, contractDate: null }); assert.deepEqual(merged, { stage: "Under Evaluation", contractDate: "8 Sep 2026" }); });
test("a null follow-up scrape does not erase stored result metadata", () => { assert.deepEqual(preserveBidassistResultMetadata({ stage: "Under Evaluation", contractDate: "2026-09-08" }, { stage: null, contractDate: null }), { stage: "Under Evaluation", contractDate: "2026-09-08" }); });
