import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Locator, Page } from "playwright";
import { closeBidassistSession, ensureBidassistLoggedIn, launchBidassistPersistentSession } from "./bidassistAuth.js";
import { loadBidassistConfig } from "./bidassistConfig.js";
import { isAwardedBidder, parseBidassistAmount, parseBidderRank } from "./bidassistResultParser.js";
import { persistBidassistResult, type ResultBidder, type ResultDocument } from "./bidassistResultStore.js";
import { downloadAndStoreBidassistAoc } from "./bidassistAocStorage.js";
import { getSupabaseAdminClient, isSupabaseConfigured } from "../supabase/client.js";
import { Logger, safeErrorMessage } from "../logger.js";
const RESULTS_URL="https://bidassist.com/tender-results/all-tenders/active";
type Tender={id:string;reference_no:string|null;source_tender_id:string;raw_metadata:Record<string,unknown>};
const esc=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const body=async(l:Locator)=>(await l.innerText().catch(()=>"")).replace(/[^\S\r\n]+/g," ").replace(/\n{2,}/g,"\n").trim();
const val=(s:string,n:string)=>s.match(new RegExp(`${n}\\s*(?::|-)?\\s*([^\\n]+)`,"i"))?.[1]?.trim()??null;
const idOf=(t:Tender)=>t.reference_no?.trim()||Object.values(t.raw_metadata).find(v=>typeof v==="string"&&/GEM\//i.test(v)) as string|undefined;
function parseBidders(s:string):ResultBidder[]{return s.split(/(?=Bidder Name\b)/i).slice(1).map(raw=>{const bid=val(raw,"Bid Value"),award=val(raw,"Award Amount");return{name:val(raw,"Bidder Name")??"",address:val(raw,"Bidder Address")??val(raw,"Address"),bid:bid===null?undefined:parseBidassistAmount(bid),award:award===null?undefined:parseBidassistAmount(award),rank:parseBidderRank(raw),status:val(raw,"Status"),awarded:isAwardedBidder(raw),raw:{displayed:raw}}}).filter(x=>x.name)}
async function findDetail(page:Page,id:string){const items=page.getByText(new RegExp(esc(id),"i"));for(let i=(await items.count())-1;i>=0;i--){const item=items.nth(i);for(let up=1;up<12;up++){const card=item.locator("xpath="+Array(up).fill("..").join("/"));const text=await body(card);if(!text.includes(id))continue;for(let j=0,n=await card.locator("a[href]").count();j<n;j++){const link=card.locator("a[href]").nth(j),title=await body(link);if(/tender\s+result/i.test(title))return{card,href:await link.getAttribute("href"),title}}}}return null}
async function pageDocuments(page:Page):Promise<ResultDocument[]>{const rows:ResultDocument[]=[];const links=page.locator("a[href]");for(let i=0,n=await links.count();i<n;i++){const l=links.nth(i),name=await body(l),href=await l.getAttribute("href");if(!/\.(pdf|html?|docx?|xlsx?|xls|csv|txt|zip)\b|document/i.test(name))continue;rows.push({name,fileName:name.match(/[^/\\]+\.[a-z0-9]+/i)?.[0]??null,type:name.split(".").pop()?.toUpperCase()??null,sourceUrl:href?new URL(href,page.url()).toString():null,downloadStatus:"METADATA_ONLY",raw:{sourcePageUrl:page.url()}})}return[...new Map(rows.map(x=>[`${x.sourceUrl}|${x.name}`,x])).values()]}
async function scrape(page:Page,t:Tender,logger:Logger,config:ReturnType<typeof loadBidassistConfig>){const id=idOf(t);if(!id)throw new Error("Missing BidAssist identifier");const url=`${RESULTS_URL}?filter=KEYWORD:${encodeURIComponent(id)}&sort=RELEVANCE:DESC`;await page.goto(url,{waitUntil:"domcontentloaded",timeout:60000});await page.getByText(new RegExp(esc(id),"i")).last().waitFor({state:"visible",timeout:15000});const match=await findDetail(page,id);if(!match)throw new Error("RESULT_DISCOVERY_FAILED");const detailUrl=new URL(match.href??"",page.url()).toString();await page.goto(detailUrl,{waitUntil:"domcontentloaded",timeout:60000});let text=await body(page.locator("body"));const expected=Number(val(text,"Number of Bids")?.match(/\d+/)?.[0]??"");for(let i=0;i<4;i++){await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await page.waitForTimeout(400)}text=await body(page.locator("body"));const bidders=parseBidders(text);const parsedDocs=await pageDocuments(page);logger.info(`[BidAssist] Expected bidders: ${expected}; parsed bidders: ${bidders.length}; AOC entries found: ${parsedDocs.length}`);const docs=await downloadAndStoreBidassistAoc({page,tenderId:t.id,awardId:id,detailUrl:page.url(),config,logger,documents:parsedDocs});logger.info(`[BidAssist] documents actually stored: ${docs.filter(d=>d.storageUrl).length}`);await persistBidassistResult({tenderId:t.id,state:bidders.length||docs.length?"SCRAPED":"NO_AOC_YET",sourceUrl:page.url(),stage:val(text,"Result Stage")??undefined,contractDate:undefined,contract:(()=>{const a=val(text,"Contract Amount");return a?parseBidassistAmount(a):undefined})(),numberOfBids:Number.isFinite(expected)?expected:null,bidders,documents:docs,raw:{awardId:id,resultTitle:match.title,detailUrl:page.url()}})}
export async function runBidassistResultsAgent(options:{tenderId?:string;limit?:number}={}){if(!isSupabaseConfigured())throw new Error("Supabase is not configured");const db=getSupabaseAdminClient();let q=db.from("agenttender_tenders").select("id,reference_no,source_tender_id,raw_metadata").eq("qualification_status","SUBMITTED");if(options.tenderId)q=q.eq("id",options.tenderId);const {data,error}=await q.limit(options.limit??1);if(error)throw new Error(error.message);const config=loadBidassistConfig(),logger=new Logger(config.logRoot,"BidAssistResults"),session=await launchBidassistPersistentSession({config,logger});let failed=0;try{await ensureBidassistLoggedIn({page:session.page,context:session.context,config,logger});for(const t of(data??[])as Tender[]){try{await scrape(session.page,t,logger,config)}catch(e){failed++;await persistBidassistResult({tenderId:t.id,state:"ERROR",reason:safeErrorMessage(e)}).catch(()=>undefined);logger.error(safeErrorMessage(e))}}}finally{await closeBidassistSession(session)}return{processed:(data??[]).length,failed}}
const invoked=process.argv[1]?path.resolve(process.argv[1]):"";if(invoked&&path.resolve(fileURLToPath(import.meta.url))===invoked){const tenderId=process.argv.find(v=>v.startsWith("--tender-id="))?.split("=")[1];void runBidassistResultsAgent({tenderId,limit:1}).then(console.log).catch(e=>{console.error(safeErrorMessage(e));process.exitCode=1})}
